<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CJNET.PrintHelper</AssemblyName>
    <RootNamespace>CJNET.PrintHelper</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>CJNET.ico</ApplicationIcon>
    <Version>0.3.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CJNET.PrintHelper.SmokeTests" />
  </ItemGroup>
</Project>
